---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: svc-aks-mysql-st01
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  azureFile:
    secretName: aks01st01prd01-secret
    shareName: aks01mysql01share
    readOnly: false
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
  - mfsymlinks
  - nobrl

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aks-mysql-st01
  namespace: site-empresa
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 20Gi      
