apiVersion: v1
kind: Service
metadata:
  name: svc-aks01-wp-01
  namespace: site-empresa
  labels:
    app: wordpress
spec:
  externalTrafficPolicy: Cluster
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: wordpress
    tier: frontend
  sessionAffinity: None
  type: LoadBalancer
---