---
apiVersion: v1
kind: Service
metadata:
  name: svc-aks01-mysql
  namespace: site-empresa
  labels:
    app: wordpress
spec:
  ports:
    - port: 3306
  selector:
    app: wordpress
    tier: mysql
  clusterIP: None
